# Generated by Django 3.1.1 on 2025-01-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='pfp_image',
        ),
    ]
