# Generated by Django 3.1.1 on 2025-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250110_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='post_images'),
            preserve_default=False,
        ),
    ]
